Resources:
  MyEKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: production-pwrtrckr
      RoleArn: arn:aws:iam::320442627588:role/AWsEKSClusterRole
      ResourcesVpcConfig:
        SubnetIds:
          - Fn::ImportValue: MyPublicSubnet1Id
          - Fn::ImportValue: MyPrivateSubnet1Id
          - Fn::ImportValue: MyPublicSubnet2Id
          - Fn::ImportValue: MyPrivateSubnet2Id         
        SecurityGroupIds:
          - Fn::ImportValue: MySecurityGroupId
      Version: "1.26"
