Resources:
  MyNodeGroup:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: production-pwrtrckr
      NodegroupName: my-eks-node-group
      ScalingConfig:
        DesiredSize: 2
        MaxSize: 3
        MinSize: 1
      Subnets:      
        - Fn::ImportValue: MyPublicSubnet1Id
        - Fn::ImportValue: MyPublicSubnet2Id
      InstanceTypes:
        - t2.small
      NodeRole: arn:aws:iam::320442627588:role/EKSNODEGROUP
